2025-05-15 23:28:49,310-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-15 23:28:49,326-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-15 23:28:49,752-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-15 23:29:13,105-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-15 23:29:13,110-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 00:14:53,805-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 00:14:54,140-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 00:14:54,149-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 00:18:45,646-nicegui-30-ERROR: Timer cancelled because client is not connected after 60.0 seconds
2025-05-16 00:18:45,945-nicegui-30-ERROR: Timer cancelled because client is not connected after 60.0 seconds
2025-05-16 00:22:31,810-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 00:22:31,817-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:18:34,996-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:18:35,006-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:18:35,432-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:18:53,554-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:18:53,559-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:19:24,035-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:19:24,044-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:20:15,840-nicegui-131-ERROR: JavaScript did not respond within 1.0 s
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wait_for2/impl.py", line 61, in _cancel_and_wait2
    fut_result = await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/javascript_request.py", line 30, in __await__
    yield from helpers.wait_for(self._event.wait(), self.timeout).__await__()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/helpers.py", line 120, in wait_for
    return await wait_for2.wait_for(fut, timeout)
  File "/usr/local/lib/python3.10/dist-packages/wait_for2/impl.py", line 172, in wait_for
    return await _cancel_and_wait2(fut, loop, False, race_handler)
  File "/usr/local/lib/python3.10/dist-packages/wait_for2/impl.py", line 67, in _cancel_and_wait2
    raise TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/client.py", line 319, in result_with_client
    await result
  File "/usr/local/lib/python3.10/dist-packages/nicegui/page_layout.py", line 135, in _request_value
    self.value = await context.client.run_javascript(
  File "/usr/local/lib/python3.10/dist-packages/nicegui/client.py", line 225, in send_and_wait
    return await JavaScriptRequest(request_id, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/nicegui/javascript_request.py", line 32, in __await__
    raise TimeoutError(f'JavaScript did not respond within {self.timeout:.1f} s') from e
TimeoutError: JavaScript did not respond within 1.0 s
2025-05-16 10:20:18,438-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:20:18,610-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:23:46,951-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:23:46,958-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:25:08,162-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:25:08,351-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:26:02,821-nicegui-30-ERROR: Timer cancelled because client is not connected after 60.0 seconds
2025-05-16 10:26:59,471-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:26:59,788-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:26:59,798-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:15,809-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:16,130-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:28,151-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:28,157-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:40,309-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:40,316-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:46,159-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:46,167-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:57,042-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:28:57,324-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 10:29:01,140-nicegui-30-ERROR: Timer cancelled because client is not connected after 60.0 seconds
2025-05-16 23:42:14,440-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:14,451-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:16,116-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:22,501-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:22,509-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:23,094-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:23,113-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:53,268-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:53,273-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:42:55,015-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:43:02,558-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:43:02,564-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:43:02,947-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:43:02,956-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:02,771-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:04,222-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:04,241-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:06,188-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:06,195-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:06,609-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:45:06,626-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:11,008-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:12,465-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:12,477-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:14,999-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:15,340-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:15,360-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:55,859-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:55,865-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:57,333-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:59,828-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:53:59,833-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:05,604-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:05,610-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:07,078-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:09,269-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:09,647-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-16 23:54:09,656-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
