2025-05-14 18:49:59,554-mq.mq_impl-84-INFO: Connected with result code 0
2025-05-14 18:50:04,375-mq.mq_impl-84-INFO: Connected with result code 0
2025-05-14 18:50:06,562-nicegui-29-WARNING: Could not load storage file /smart_school_web/.nicegui/storage-user-8b2049fe-5e90-4c70-8587-063fbf5f67c0.json
2025-05-14 18:50:10,159-watchfiles.main-308-INFO: 2 changes detected
2025-05-14 18:50:14,033-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-14 18:50:14,450-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-14 18:50:14,457-nicegui-131-ERROR: Type is not JSON serializable: function
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nicegui/background_tasks.py", line 77, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/nicegui/persistence/file_persistent_dict.py", line 51, in async_backup
    await f.write(json.dumps(self, indent=self.indent))
  File "/usr/local/lib/python3.10/dist-packages/nicegui/json/orjson_wrapper.py", line 40, in dumps
    return orjson.dumps(obj, option=opts, default=_orjson_converter).decode('utf-8')
TypeError: Type is not JSON serializable: function
2025-05-14 18:50:14,817-watchfiles.main-308-INFO: 4 changes detected
